#!/usr/bin/env python3
"""Analyze detector performance for img2img outputs generated by im2im_permission.py."""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import warnings

try:
    import statsmodels.api as sm
    HAS_STATSMODELS = True
except Exception:
    HAS_STATSMODELS = False

try:
    from sklearn.linear_model import LogisticRegression
    HAS_SKLEARN = True
except Exception:
    HAS_SKLEARN = False


DEFAULT_CSV = Path("/media/CrispyMcMarkInc/detector_img2img_im2im_permission_results.csv")
DEFAULT_FIGURES_DIR = Path("/media/CrispyMcMarkInc/figures/img2img")


sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)


def prepare_results(df: pd.DataFrame) -> pd.DataFrame:
    result = df.copy()

    for column in ("confidence", "elapsed_time", "steps", "guidance", "strength", "seed"):
        if column in result.columns:
            result[column] = pd.to_numeric(result[column], errors="coerce")

    if "batch_label" not in result.columns:
        result["batch_label"] = "unknown"
    if "model" not in result.columns:
        result["model"] = "unknown"
    if "quantization" not in result.columns:
        result["quantization"] = "unknown"
    if "detector" not in result.columns:
        result["detector"] = "unknown"

    return result


def build_summary(df: pd.DataFrame) -> pd.DataFrame:
    summary_rows = []

    for detector in sorted(df["detector"].dropna().unique()):
        sub = df[df["detector"] == detector]
        total = len(sub)
        fake_predictions = (sub["prediction"] == "fake").sum()
        real_predictions = (sub["prediction"] == "real").sum()
        fake_rate = fake_predictions / total if total > 0 else 0
        avg_conf_fake = sub.loc[sub["prediction"] == "fake", "confidence"].mean()
        avg_conf_all = sub["confidence"].mean()
        avg_elapsed = sub["elapsed_time"].mean() if "elapsed_time" in sub.columns else None

        summary_rows.append(
            {
                "detector": detector,
                "total": total,
                "fake_predictions": fake_predictions,
                "real_predictions": real_predictions,
                "fake_rate": fake_rate,
                "avg_confidence_on_fake_predictions": avg_conf_fake,
                "avg_confidence_overall": avg_conf_all,
                "avg_elapsed_time": avg_elapsed,
            }
        )

    return pd.DataFrame(summary_rows)


def build_generation_summary(df: pd.DataFrame) -> pd.DataFrame:
    group_cols = ["model", "quantization", "steps", "guidance", "strength", "detector"]
    available_group_cols = [col for col in group_cols if col in df.columns]
    if len(available_group_cols) < 2:
        return pd.DataFrame()

    def summarize_group(group: pd.DataFrame) -> pd.Series:
        fake_predictions = group[group["prediction"] == "fake"]
        return pd.Series(
            {
                "sample_count": len(group),
                "fake_rate": (group["prediction"] == "fake").mean(),
                "avg_confidence_on_fake_predictions": fake_predictions["confidence"].mean(),
                "avg_confidence_overall": group["confidence"].mean(),
                "avg_elapsed_time": group["elapsed_time"].mean() if "elapsed_time" in group.columns else None,
            }
        )

    return df.groupby(available_group_cols).apply(summarize_group).reset_index()


def plot_metric_grid_seaborn(
    df: pd.DataFrame,
    metric: str,
    title: str,
    output_path: Path,
    cmap: str,
    formatter,
) -> None:
    models = [model for model in sorted(df["model"].dropna().unique()) if model != "unknown"]
    if not models or metric not in df.columns:
        return

    n_models = len(models)
    n_cols = 2 if n_models > 1 else 1
    n_rows = (n_models + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(8 * n_cols, 5 * n_rows), constrained_layout=True)
    axes = [axes] if n_models == 1 else list(axes.flat)

    vmin = df[metric].min()
    vmax = df[metric].max()

    for axis_index, axis in enumerate(axes):
        if axis_index >= len(models):
            axis.axis("off")
            continue

        model = models[axis_index]
        subm = df[df["model"] == model]
        pivot = subm.pivot_table(index="detector", columns="quantization", values=metric, aggfunc="mean")

        if pivot.empty:
            axis.axis("off")
            continue

        ordered_cols = [col for col in ["fp16", "fp8", "fp4"] if col in pivot.columns]
        pivot = pivot[ordered_cols]
        annot_data = pivot.map(lambda value: formatter(value) if pd.notna(value) else "")

        sns.heatmap(
            pivot,
            ax=axis,
            cmap=cmap,
            annot=annot_data,
            fmt="",
            vmin=vmin,
            vmax=vmax,
            linewidths=1,
            linecolor="white",
            cbar_kws={"shrink": 0.8},
            annot_kws={"fontsize": 11, "fontweight": "bold"},
        )

        axis.set_title(f"Model: {model}", fontweight="bold", fontsize=14, pad=10)
        axis.set_xlabel("Quantization", fontsize=12, fontweight="semibold")
        axis.set_ylabel("Detector", fontsize=12, fontweight="semibold")
        axis.tick_params(axis="x", rotation=0, labelsize=11)
        axis.tick_params(axis="y", rotation=0, labelsize=11)

    fig.suptitle(title, fontsize=18, fontweight="extra bold")
    fig.patch.set_facecolor("white")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def save_figures(df: pd.DataFrame, output_dir: Path = DEFAULT_FIGURES_DIR) -> None:
    if df.empty:
        return

    base = df.groupby(["model", "quantization", "detector"]).apply(
        lambda group: pd.Series(
            {
                "fake_rate": (group["prediction"] == "fake").mean(),
                "avg_confidence_on_fake_predictions": group.loc[group["prediction"] == "fake", "confidence"].mean(),
                "avg_elapsed_time": group["elapsed_time"].mean() if "elapsed_time" in group.columns else None,
            }
        )
    ).reset_index()

    plot_metric_grid_seaborn(
        base,
        metric="fake_rate",
        title="Img2img Detector True Positive Rate by Model and Quantization",
        output_path=output_dir / "img2img_permission_fake_rate_by_model_quantization_detector.png",
        cmap="mako",
        formatter=lambda value: f"{value:.1%}",
    )

    plot_metric_grid_seaborn(
        base,
        metric="avg_confidence_on_fake_predictions",
        title="Img2img Average Confidence on Fake Predictions",
        output_path=output_dir / "img2img_permission_confidence_by_model_quantization_detector.png",
        cmap="flare",
        formatter=lambda value: f"{value:.2f}",
    )

    if "avg_elapsed_time" in base.columns and base["avg_elapsed_time"].notna().any():
        plot_metric_grid_seaborn(
            base,
            metric="avg_elapsed_time",
            title="Img2img Average Detection Time",
            output_path=output_dir / "img2img_permission_elapsed_time_by_model_quantization_detector.png",
            cmap="crest",
            formatter=lambda value: f"{value:.2f}s",
        )


def main(csv_path: str) -> None:
    csv_file = Path(csv_path)
    if not csv_file.is_file():
        raise FileNotFoundError(f"CSV not found: {csv_file}")

    df = pd.read_csv(csv_file)
    df = prepare_results(df)

    print("\n=== Img2img Detector Performance by Model and Quantization ===")
    for model in sorted(df["model"].unique()):
        if model == "unknown":
            continue
        print(f"\n--- Generation Model: {model} ---")
        subm = df[df["model"] == model]
        model_summary = build_summary(subm)
        print(model_summary.to_string(index=False))

    print("\n=== Img2img Detector Performance Overall ===")
    overall_summary = build_summary(df)
    print(overall_summary.to_string(index=False))

    generation_summary = build_generation_summary(df)
    if not generation_summary.empty:
        summary_path = DEFAULT_FIGURES_DIR / "img2img_permission_generation_summary.csv"
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        generation_summary.sort_values(
            by=["fake_rate", "avg_confidence_on_fake_predictions"],
            ascending=[False, False],
        ).to_csv(summary_path, index=False)
        print(f"\nSaved generation-comparison summary to {summary_path}")

        print("\n=== Best Generation Combinations by Fake Rate ===")
        top_rows = generation_summary.sort_values(
            by=["fake_rate", "avg_confidence_on_fake_predictions"],
            ascending=[False, False],
        )
        print(top_rows.to_string(index=False))

        # Additional ranking and influence analysis
        detailed_out = DEFAULT_FIGURES_DIR / "img2img_permission_generation_summary_detailed.csv"
        generation_summary.to_csv(detailed_out, index=False)
        print(f"Saved detailed generation summary to {detailed_out}")

        ranked = generation_summary.sort_values(by=["fake_rate", "avg_confidence_on_fake_predictions"], ascending=[False, False])
        top = ranked.head(20)
        bottom = ranked.tail(20)
        (DEFAULT_FIGURES_DIR / "top_generation_combos.csv").write_text(top.to_csv(index=False))
        (DEFAULT_FIGURES_DIR / "bottom_generation_combos.csv").write_text(bottom.to_csv(index=False))

        print("\nTop 10 combos:")
        print(top.head(10).to_string(index=False))
        print("\nBottom 10 combos:")
        print(bottom.tail(10).to_string(index=False))

        # Influence tests per detector
        print("\nRunning influence checks per detector (steps/guidance/strength -> prediction)...")
        influence_rows = []
        for detector in sorted(df["detector"].dropna().unique()):
            sub = df[df["detector"] == detector].copy()
            sub = sub.dropna(subset=["prediction"]) 
            if sub.empty:
                continue
            sub["y"] = (sub["prediction"] == "fake").astype(int)
            for col in ("steps", "guidance", "strength"):
                if col in sub.columns:
                    sub[col] = pd.to_numeric(sub[col], errors="coerce")

            features = [c for c in ("steps", "guidance", "strength") if c in sub.columns]
            if not features or sub["y"].nunique() < 2:
                print(f"Skipping detector {detector}: insufficient data for influence test.")
                continue

            X = sub[features].fillna(sub[features].median())
            y = sub["y"].values

            res = {"detector": detector, "n": len(sub)}
            try:
                if HAS_STATSMODELS:
                    Xc = sm.add_constant(X)
                    with warnings.catch_warnings():
                        warnings.simplefilter("ignore")
                        model = sm.Logit(y, Xc).fit(disp=0)
                    for name in ["const"] + features:
                        coef = model.params.get(name, None)
                        pval = model.pvalues.get(name, None)
                        res[f"coef_{name}"] = float(coef) if coef is not None else None
                        res[f"p_{name}"] = float(pval) if pval is not None else None
                elif HAS_SKLEARN:
                    clf = LogisticRegression(max_iter=1000)
                    clf.fit(X, y)
                    for name, coef in zip(features, clf.coef_[0]):
                        res[f"coef_{name}"] = float(coef)
                        res[f"p_{name}"] = None
                else:
                    for name in features:
                        corr = sub[["y", name]].corr(method="spearman").iloc[0,1]
                        res[f"spearman_{name}"] = float(corr) if pd.notna(corr) else None
            except Exception as e:
                res["error"] = str(e)

            influence_rows.append(res)

        infl_df = pd.DataFrame(influence_rows)
        if not infl_df.empty:
            infl_df.to_csv(DEFAULT_FIGURES_DIR / "influence_tests_by_detector.csv", index=False)
            print(f"Saved influence test results to {DEFAULT_FIGURES_DIR / 'influence_tests_by_detector.csv'}")

    save_figures(df)
    print(f"\nSaved high-resolution figures to {DEFAULT_FIGURES_DIR}")


if __name__ == "__main__":
    csv_arg = sys.argv[1] if len(sys.argv) > 1 else str(DEFAULT_CSV)
    main(csv_arg)