#!/usr/bin/env python3
"""Phase 2: Deepfake Detection Runner for img2img outputs generated by im2im_permission.py."""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Dict, List, Optional


os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")

PROJECT_ROOT = Path("/media/CrispyMcMarkInc")
TEMP_IMG_DIR = Path("/media/SSD_4TB/crispy_storage/comparative_images_img2img/")
DETECTOR_ROOT = PROJECT_ROOT / "Image-Deepfake-Detectors-Public-Library"
RESULTS_CSV = PROJECT_ROOT / "detector_img2img_im2im_permission_results.csv"

DETECTOR_PYTHON = Path(
    os.environ.get(
        "DETECTOR_PYTHON",
        str(PROJECT_ROOT / ".venvs" / "detector" / "bin" / "python"),
    )
)

DETECTOR_ENTRYPOINT = "launcher.py"
DETECTORS_TO_RUN = ["CLIP-D", "R50_TF", "NPR"]
DETECTOR_WEIGHTS = "pretrained"
SUPPORTED_IMAGE_EXTS = {".png", ".jpg", ".jpeg"}

CSV_FIELDS = [
    "batch_label",
    "source_image",
    "model",
    "quantization",
    "seed",
    "steps",
    "guidance",
    "strength",
    "detector",
    "image_path",
    "prediction",
    "confidence",
    "elapsed_time",
]

FILENAME_PATTERN = re.compile(
    r"^(?P<source>.+)_(?P<model>sd15|sd3|sd35)_(?P<quant>fp16|fp8|fp4)_seed(?P<seed>\d+)_s(?P<steps>\d+)_g(?P<guidance>[0-9]+(?:\.[0-9]+)?)_str(?P<strength>[0-9]+(?:\.[0-9]+)?)$"
)


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def initialize_results_csv() -> None:
    RESULTS_CSV.parent.mkdir(parents=True, exist_ok=True)
    with RESULTS_CSV.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_FIELDS)
        writer.writeheader()


def append_results_csv_header_if_missing() -> None:
    RESULTS_CSV.parent.mkdir(parents=True, exist_ok=True)
    if RESULTS_CSV.exists() and RESULTS_CSV.stat().st_size > 0:
        return
    with RESULTS_CSV.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_FIELDS)
        writer.writeheader()


def _available_detectors(detectors_to_run: List[str], weights_name: str) -> List[str]:
    available = []
    for detector_name in detectors_to_run:
        weight_path = DETECTOR_ROOT / "detectors" / detector_name / "checkpoint" / weights_name / "weights" / "best.pt"
        if weight_path.is_file():
            available.append(detector_name)
        else:
            logging.warning("Skipping detector %s: weights not found at %s", detector_name, weight_path)
    return available


def parse_generation_metadata(filename: str) -> Dict[str, Optional[str]]:
    stem = Path(filename).stem
    match = FILENAME_PATTERN.match(stem)
    if not match:
        return {
            "batch_label": "unknown",
            "source_image": stem,
            "model": "unknown",
            "quantization": "unknown",
            "seed": None,
            "steps": None,
            "guidance": None,
            "strength": None,
        }

    data = match.groupdict()
    batch_label = f"{data['model']}_{data['quant']}_s{data['steps']}_g{data['guidance']}_str{data['strength']}"
    return {
        "batch_label": batch_label,
        "source_image": data["source"],
        "model": data["model"],
        "quantization": data["quant"],
        "seed": data["seed"],
        "steps": data["steps"],
        "guidance": data["guidance"],
        "strength": data["strength"],
    }


def build_completion_key(batch_label: str, detector_name: str, image_path: Path) -> str:
    return f"{batch_label}|{detector_name}|{image_path.name}"


def load_completed_keys(json_out_dir: Path) -> set[str]:
    completed: set[str] = set()

    if RESULTS_CSV.is_file():
        with RESULTS_CSV.open("r", newline="", encoding="utf-8") as csv_file:
            reader = csv.DictReader(csv_file)
            for row in reader:
                batch_label = str(row.get("batch_label", "unknown"))
                detector_name = str(row.get("detector", "unknown"))
                image_path = str(row.get("image_path", ""))
                image_name = Path(image_path).name if image_path else ""
                if batch_label and detector_name and image_name:
                    completed.add(f"{batch_label}|{detector_name}|{image_name}")

    if json_out_dir.exists():
        for json_path in json_out_dir.glob("*.json"):
            stem = json_path.stem
            parts = stem.split("_")
            if len(parts) < 2:
                continue
            detector_name = parts[-2]
            image_name = parts[-1]
            batch_label = "_".join(parts[:-2])
            completed.add(f"{batch_label}|{detector_name}|{image_name}")

    return completed


def main() -> None:
    setup_logging()

    if not DETECTOR_PYTHON.is_file():
        raise FileNotFoundError(f"Detector Python not found at {DETECTOR_PYTHON}")

    images_dir = TEMP_IMG_DIR
    if not images_dir.exists():
        raise FileNotFoundError(f"Img2img output directory not found: {images_dir}")

    active_detectors = _available_detectors(DETECTORS_TO_RUN, DETECTOR_WEIGHTS)
    if not active_detectors:
        logging.error("No valid detectors found. Exiting.")
        return

    images = [p for p in images_dir.iterdir() if p.is_file() and p.suffix.lower() in SUPPORTED_IMAGE_EXTS]
    if not images:
        logging.warning("No supported images found in directory: %s", images_dir)
        return

    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--complete", action="store_true")
    args, _ = parser.parse_known_args()

    logging.info("Found %d images in %s. Starting detection...", len(images), images_dir)

    json_out_dir = images_dir / "_detect_json"
    json_out_dir.mkdir(parents=True, exist_ok=True)
    launcher = DETECTOR_ROOT / DETECTOR_ENTRYPOINT

    if args.complete:
        append_results_csv_header_if_missing()
        completed_keys = load_completed_keys(json_out_dir)
        logging.info("Loaded %d completed image/detector pairs from CSV/JSON artifacts.", len(completed_keys))
    else:
        initialize_results_csv()
        logging.info("Initialized results CSV: %s", RESULTS_CSV)
        completed_keys = set()

    with RESULTS_CSV.open("a", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_FIELDS)

        for image_path in images:
            metadata = parse_generation_metadata(image_path.name)
            batch_label = metadata["batch_label"] or "unknown"
            safe_stem = image_path.stem.replace(" ", "_")

            for detector_name in active_detectors:
                completion_key = build_completion_key(batch_label, detector_name, image_path)
                if args.complete and completion_key in completed_keys:
                    logging.info("[%s] Detect[%s] already completed, skipping %s.", batch_label, detector_name, image_path.name)
                    continue

                output_json = json_out_dir / f"{batch_label}_{detector_name}_{safe_stem}.json"
                detect_cmd = [
                    str(DETECTOR_PYTHON),
                    str(launcher),
                    "--detector",
                    detector_name,
                    "--detect",
                    "--image",
                    str(image_path),
                    "--weights",
                    DETECTOR_WEIGHTS,
                    "--output",
                    str(output_json),
                ]

                try:
                    logging.info("[%s] Detect[%s] | Command: %s", batch_label, detector_name, " ".join(detect_cmd))
                    subprocess.run(detect_cmd, cwd=str(DETECTOR_ROOT), check=True, timeout=300)

                    if output_json.is_file():
                        payload = json.loads(output_json.read_text(encoding="utf-8"))
                        writer.writerow(
                            {
                                "batch_label": batch_label,
                                "source_image": metadata["source_image"],
                                "model": metadata["model"],
                                "quantization": metadata["quantization"],
                                "seed": metadata["seed"],
                                "steps": metadata["steps"],
                                "guidance": metadata["guidance"],
                                "strength": metadata["strength"],
                                "detector": detector_name,
                                "image_path": str(image_path),
                                "prediction": payload.get("prediction"),
                                "confidence": payload.get("confidence"),
                                "elapsed_time": payload.get("elapsed_time"),
                            }
                        )
                        csv_file.flush()
                        completed_keys.add(completion_key)

                except subprocess.TimeoutExpired:
                    logging.error("[%s] Detect[%s] timed out after 300s on %s", batch_label, detector_name, image_path.name)
                except Exception as exc:
                    logging.exception("[%s] Error running detection on %s: %s", batch_label, image_path.name, exc)

    logging.info("Detection completed. Results written to %s", RESULTS_CSV)


if __name__ == "__main__":
    main()